name: CI 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Copy .env .example files 
        shell: bash 
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${2}"' _ {} \;

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run typecheck
